<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
        <PackageReference Include="Onspay.Infrastructure.DomainEvents" Version="1.0.16" />
        <PackageReference Include="Onspay.Infrastructure.Inbox" Version="1.0.16" />
        <PackageReference Include="Onspay.Infrastructure.Outbox" Version="1.0.16" />
        <PackageReference Include="Onspay.Infrastructure.Messaging.RabbitMq" Version="1.0.16" />
        <PackageReference Include="Onspay.Infrastructure.Correlation" Version="1.0.16" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

</Project>
