<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Onspay.Cqrs" Version="1.0.23" />
        <PackageReference Include="Onspay.Infrastructure.Outbox" Version="1.0.23" />
        <PackageReference Include="Onspay.Infrastructure.Inbox" Version="1.0.23" />
        <PackageReference Include="Kafadanat.Contracts" Version="2.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

</Project>
